//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int Cards_ID { get; set; }
        public int Users_ID { get; set; }
        public int Object_ID { get; set; }
        public string MakeDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Object Object { get; set; }
    }
}
