//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards_TSO
    {
        public int Id { get; set; }
        public int TSO_ID { get; set; }
        public byte Number { get; set; }
        public int Cards_ID { get; set; }
    
        public virtual TSO TSO { get; set; }
        public virtual Cards Cards { get; set; }
    }
}
