//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> CardsSet { get; set; }
        public virtual DbSet<Object> ObjectSet { get; set; }
        public virtual DbSet<Streets> StreetsSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<TSOGroup> TSOGroupSet { get; set; }
        public virtual DbSet<TSO> TSOSet { get; set; }
        public virtual DbSet<PKP> PKPSet { get; set; }
        public virtual DbSet<Branch> BranchSet { get; set; }
        public virtual DbSet<PKPModels> PKPModelsSet { get; set; }
        public virtual DbSet<Modules> ModulesSet { get; set; }
        public virtual DbSet<PKP_Modules> PKP_ModulesSet { get; set; }
        public virtual DbSet<Cards_TSO> Cards_TSOSet { get; set; }
    }
}
