//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Limb = new HashSet<Limb>();
            this.Cards = new HashSet<Cards>();
        }
    
        public int Equipment_ID { get; set; }
        public byte[] Data { get; set; }
        public double Amount { get; set; }
    
        public virtual ICollection<Limb> Limb { get; set; }
        public virtual ICollection<Cards> Cards { get; set; }
    }
}
