//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limb
    {
        public int Limb_ID { get; set; }
        public byte Number { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
        public int CardsCards_ID { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
