//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int Object_ID { get; set; }
        public string Owner { get; set; }
        public string Name { get; set; }
        public string Home { get; set; }
        public string Corp { get; set; }
        public string Room { get; set; }
        public int Streets_ID { get; set; }
        public int Cards_ID { get; set; }
    
        public virtual Streets Streets { get; set; }
        public virtual Cards Cards { get; set; }
    }
}
