//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKP
    {
        public PKP()
        {
            this.PKP_Modules = new HashSet<PKP_Modules>();
        }
    
        public int PKP_ID { get; set; }
        public string Serial { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public System.DateTime Date { get; set; }
        public double UUAmount { get; set; }
        public int PKPModels_ID { get; set; }
        public int Cards_ID { get; set; }
    
        public virtual PKPModels PKPModels { get; set; }
        public virtual ICollection<PKP_Modules> PKP_Modules { get; set; }
        public virtual Cards Cards { get; set; }
    }
}
