//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKP
    {
        public PKP()
        {
            this.Cards = new HashSet<Cards>();
            this.PKP_Modules = new HashSet<PKP_Modules>();
        }
    
        public int PKP_ID { get; set; }
        public string Serial { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public System.DateTime Date { get; set; }
        public double UUAmount { get; set; }
        public int PKPModels_ID { get; set; }
    
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual PKPModels PKPModels { get; set; }
        public virtual ICollection<PKP_Modules> PKP_Modules { get; set; }
    }
}
