//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKPModels
    {
        public PKPModels()
        {
            this.PKP = new HashSet<PKP>();
        }
    
        public int PKPModels_ID { get; set; }
        public string Name { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<PKP> PKP { get; set; }
    }
}
