//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        public Streets()
        {
            this.Object = new HashSet<Object>();
        }
    
        public int Streets_ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Object> Object { get; set; }
    }
}
