//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSO
    {
        public TSO()
        {
            this.Visible = true;
            this.Equipment_TSO = new HashSet<Cards_TSO>();
        }
    
        public int TSO_ID { get; set; }
        public string Name { get; set; }
        public bool Visible { get; set; }
        public int Group_ID { get; set; }
    
        public virtual TSOGroup TSOGroup { get; set; }
        public virtual ICollection<Cards_TSO> Equipment_TSO { get; set; }
    }
}
