//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSO
    {
        public TSO()
        {
            this.Visible = true;
            this.Equipment_TSO = new HashSet<Cards_TSO>();
        }
    
        public int TSO_ID { get; set; }
        public string Name { get; set; }
        public bool Visible { get; set; }
        public int Group_ID { get; set; }
    
        public virtual TSOGroup TSOGroup { get; set; }
        public virtual ICollection<Cards_TSO> Equipment_TSO { get; set; }
    }
}
