//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSOGroup
    {
        public TSOGroup()
        {
            this.Visible = true;
            this.TSO = new HashSet<TSO>();
        }
    
        public int TSOGroup_ID { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<TSO> TSO { get; set; }
    }
}
