//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSOGroup
    {
        public TSOGroup()
        {
            this.Visible = true;
            this.TSO = new HashSet<TSO>();
        }
    
        public int TSOGroup_ID { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
        public byte Type { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<TSO> TSO { get; set; }
    }
}
