//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Cards = new HashSet<Cards>();
        }
    
        public int Users_ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Place { get; set; }
    
        public virtual ICollection<Cards> Cards { get; set; }
    }
}
