//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Cards = new HashSet<Cards>();
        }
    
        public int Users_ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Place { get; set; }
    
        public virtual ICollection<Cards> Cards { get; set; }
    }
}
