//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public Cards()
        {
            this.Branch = new HashSet<Branch>();
            this.Cards_TSO = new HashSet<Cards_TSO>();
            this.Object = new HashSet<Object>();
            this.PKP = new HashSet<PKP>();
        }
    
        public int Cards_ID { get; set; }
        public int Users_ID { get; set; }
        public System.DateTime MakeDate { get; set; }
        public double Amount { get; set; }
        public string OwnerView { get; set; }
        public string ObjectView { get; set; }
        public string AddressView { get; set; }
        public string PKPView { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Branch> Branch { get; set; }
        public virtual ICollection<Cards_TSO> Cards_TSO { get; set; }
        public virtual ICollection<Object> Object { get; set; }
        public virtual ICollection<PKP> PKP { get; set; }
    }
}
